In [1]:
#inspect general information of an array
import numpy as np
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x16814467230
byteorder:  little
byteswap:  False
type: int64
None


In [3]:
print(arr.dtype)
print(arr.shape)
print(len(arr))
print(arr.ndim)
print(arr.size)
print(arr.itemsize)#no of bytes of each element
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)


int64
(2, 3)
2
2
6
8
48


SAMPLING METHODS:

In [7]:

np.random.seed(123)
rs = np.random.RandomState(321)
rs.rand(10)
#generate a random sample from interval [0, 1) in a given shape
# generate a random scalar

#print(np.random.rand(3))  
    

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

In [8]:
print(np.random.rand(3))  

[0.69646919 0.28613933 0.22685145]


In [9]:
#generate a sample from the standard normal distribution (mean = 0, var = 1)
print(np.random.randn(3,3))

[[ 1.73837013  0.4064541   0.32210607]
 [-0.05151772 -0.20420096  1.97934843]
 [-1.61930007 -1.11396442 -0.44744072]]


In [10]:
#generate an array of random integers in a given interval [low, high)
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[5 1 1]


In [11]:
#generate an array of random floating-point numbers in the interval [0.0, 1.0)
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.73799541 0.18249173 0.17545176 0.53155137 0.53182759 0.63440096
 0.84943179 0.72445532 0.61102351 0.72244338]
[0.32295891 0.36178866 0.22826323 0.29371405 0.63097612 0.09210494
 0.43370117 0.43086276 0.4936851  0.42583029]
[0.31226122 0.42635131 0.89338916 0.94416002 0.50183668 0.62395295
 0.1156184  0.31728548 0.41482621 0.86630916]
[0.25045537 0.48303426 0.98555979 0.51948512 0.61289453 0.12062867
 0.8263408  0.60306013 0.54506801 0.34276383]


In [14]:
#generate a random sample from a given 1-D array
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))
print(np.random.choice(3, 10))
print(np.random.choice([1,2,3], 10))
arr = np.array(range(10))
print(arr)


[1 1 1 1 1 1 1 1 1 1]
[2 2 1 2 0 2 2 1 1 2]
[3 1 2 2 1 2 1 2 3 3]
[0 1 2 3 4 5 6 7 8 9]


In [12]:
np.random.shuffle(arr)
print(arr)

[[4 5 6]
 [1 2 3]]


In [15]:
#generate a permutation of an array
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [4 2 7 6 9 5 3 0 1 8]


element-wise addition, subtraction, multiplication and division

In [17]:
arr = np.random.rand(5,5)
print(arr + 2)
print(arr - 2)
print(arr * 2)
print(arr / 2)

[[2.67792545 2.80912668 2.86857215 2.41799246 2.05893816]
 [2.478459   2.52115943 2.58063202 2.309199   2.91988263]
 [2.6553475  2.34924138 2.54109404 2.4490534  2.28232096]
 [2.29587653 2.56348098 2.71519128 2.51761868 2.35204183]
 [2.63277886 2.87311902 2.16788844 2.98747832 2.34941493]]
[[-1.32207455 -1.19087332 -1.13142785 -1.58200754 -1.94106184]
 [-1.521541   -1.47884057 -1.41936798 -1.690801   -1.08011737]
 [-1.3446525  -1.65075862 -1.45890596 -1.5509466  -1.71767904]
 [-1.70412347 -1.43651902 -1.28480872 -1.48238132 -1.64795817]
 [-1.36722114 -1.12688098 -1.83211156 -1.01252168 -1.65058507]]
[[1.35585089 1.61825336 1.73714431 0.83598491 0.11787631]
 [0.95691801 1.04231886 1.16126404 0.618398   1.83976525]
 [1.31069501 0.69848277 1.08218809 0.89810679 0.56464192]
 [0.59175305 1.12696197 1.43038256 1.03523735 0.70408366]
 [1.26555772 1.74623804 0.33577689 1.97495664 0.69882986]]
[[0.33896272 0.40456334 0.43428608 0.20899623 0.02946908]
 [0.2392295  0.26057971 0.29031601 0.1545995

In [22]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1) #adding 2 arrays.
print(arr1)

print(np.sum(arr1, axis=0))    #gives all eliments total.
print()

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
33

[1 2 3]
[1 4 9]


In [ ]:
#element-wise exponentiation
print(np.exp(arr))
# natural log
print(np.log(arr))    

In [19]:
# base 2
print(np.log2(arr))   

[[-0.56080147 -0.3055625  -0.20328239 -1.25845119 -4.08465428]
 [-1.06353278 -0.94020332 -0.78430396 -1.69339245 -0.12047831]
 [-0.60966799 -1.51770357 -0.88604873 -1.15504109 -1.82459185]
 [-1.75693286 -0.82756117 -0.48359895 -0.95003842 -1.50618124]
 [-0.6602267  -0.19574977 -2.57442516 -0.01817902 -1.51698684]]


In [20]:
print(np.sin(arr))
print(np.cos(arr))

[[0.62717856 0.72368474 0.76340745 0.40592657 0.05890404]
 [0.46041177 0.49788598 0.54855249 0.30429572 0.79553051]
 [0.60943479 0.34218509 0.51507406 0.43411297 0.27858547]
 [0.2915784  0.53413225 0.65576184 0.49481217 0.34481513]
 [0.59138787 0.76633644 0.16710086 0.8346397  0.34234815]]
[[0.77887551 0.69013071 0.64591723 0.9139057  0.99826365]
 [0.88770547 0.8672425  0.83611612 0.95257762 0.60591354]
 [0.7928362  0.93963257 0.85714568 0.90085844 0.96041144]
 [0.95654693 0.84540093 0.75496782 0.86899995 0.93867062]
 [0.80638724 0.64243946 0.98593981 0.5507963  0.93957317]]


In [24]:
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))




[3 2 4 1 0]
[0 4 0 4 1]
[4 3 4 0 2]
[2 4 0 2 3]


In [25]:
print(np.argmin(arr))
print(np.argmax(arr))


4
23


In [26]:
#compute eliment wise min and max
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


In [27]:
#split fractional and integral parts of a floating-point array
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.26205128 0.65461542 0.05353288 0.86944648 0.11318135 0.99407772
 0.27551385 0.1733492  0.41827619 0.56083012]
integral:  [8. 0. 0. 8. 9. 1. 0. 8. 2. 0.]


In [29]:
#print(np.mean(arr))
#print(np.median(arr, axis=1))

arr1 = np.random.rand(100)
print(arr1)

# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[1.81811530e-01 5.21010875e-01 4.79334171e-01 3.13542491e-01
 9.96692091e-02 5.96552664e-01 2.48169887e-01 6.04340164e-01
 3.05113646e-01 8.97304939e-01 5.82015328e-01 7.12492426e-01
 6.83615475e-01 9.46620897e-01 9.13231256e-01 5.12549095e-02
 3.80315483e-01 5.63856542e-01 1.32573740e-01 5.75135286e-01
 3.22567748e-01 9.83927564e-01 5.75665818e-01 6.29727634e-01
 4.01012276e-01 7.44630063e-01 4.01185925e-01 7.65475124e-01
 9.82431236e-01 1.68116767e-01 4.74594684e-01 5.48940484e-01
 4.36107340e-01 2.96731298e-01 3.93563740e-01 8.38081128e-01
 6.51642561e-01 9.53896933e-01 4.77000227e-01 8.78893547e-01
 7.92207783e-01 2.65357524e-01 7.62438274e-01 8.22736395e-01
 3.52992370e-01 9.74231976e-01 6.75233356e-01 6.99379648e-01
 4.59596924e-01 6.97349172e-02 9.97980177e-01 6.37750960e-01
 6.81525830e-02 1.46137037e-01 8.38913274e-01 2.77194910e-01
 5.39450971e-01 8.04327727e-02 5.66346735e-01 3.62484911e-01
 3.18213641e-01 6.53523262e-01 3.54903002e-01 7.15256807e-01
 6.28281491e-01 9.675113

In [30]:
print(np.std(arr))

0.23614329614962726


In [31]:
# compute the overall variance
print(np.var(arr))

0.05576365631641056


In [32]:
print(np.cov(arr))#compute the covariance .

[[ 0.11055111 -0.03942352  0.02779974  0.03253574  0.00225834]
 [-0.03942352  0.05024561 -0.01777728 -0.0097359  -0.05239434]
 [ 0.02779974 -0.01777728  0.02214719 -0.00090379 -0.00463939]
 [ 0.03253574 -0.0097359  -0.00090379  0.02839576 -0.0095794 ]
 [ 0.00225834 -0.05239434 -0.00463939 -0.0095794   0.11882459]]


In [33]:
print(np.corrcoef(arr[:,0], arr[:,1]))
#compute the  correlation

[[1.         0.27381712]
 [0.27381712 1.        ]]


In [34]:
print(np.cumsum(arr, axis=0))  #cumilative sum  

[[0.67792545 0.80912668 0.86857215 0.41799246 0.05893816]
 [1.15638445 1.33028611 1.44920417 0.72719145 0.97882078]
 [1.81173196 1.67952749 1.99029822 1.17624485 1.26114174]
 [2.10760848 2.24300847 2.7054895  1.69386353 1.61318357]
 [2.74038734 3.1161275  2.87337794 2.68134185 1.9625985 ]]


In [35]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[0.67792545 0.54852757 0.47643577 0.19914656 0.01173733]
 [0.478459   0.24935342 0.14478258 0.04476663 0.04118004]
 [0.6553475  0.22887447 0.12384261 0.05561195 0.01570042]
 [0.29587653 0.1667208  0.11923726 0.06171943 0.02172782]
 [0.63277886 0.55249126 0.0927569  0.09159543 0.03200481]]


In [36]:
#compasion eliment wise.
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


slicing and indexing