In [2]:
import numpy as np
arr = np.array(range(100)).reshape((10,10))
print(arr)
print(arr[5][5])
# or more concisely
print(arr[5,5])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
55
55


In [3]:
#indexing with slicing

print(arr[1:3, 4:6])
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])   

[[14 15]
 [24 25]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [4]:
#assign a scalar to a slice by broadcasting
# efficiently assign values to specific parts of an array.
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)


[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


In [5]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [6]:
# negate the condition
#element-wise negation of boolean 
print(arr1[~bools])    


[[10 11 12 13 14]
 [20 21 22 23 24]]


In [7]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<5) | (arr2>14)])    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


FANCY INDEXING

In [11]:
arr = np.random.rand(10,10)#filled with random numbers between 0(x)& 1(y).
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])  #arr[x],[y]    
#(3, 3), (1, 2), and (2, 1) from the array arr. 


[0.93452307 0.22334132 0.78645147]


In [30]:
arr = np.array(range(16))

print(arr)

#print(arr.shape)
#whatever dimension is needed to accommodate the remaining elements and maintain the total number of elements consistent with the original array".

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [31]:
arr = arr.reshape(4,-2)

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [29]:
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)
print(arr)

(4, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [32]:
#find elements/indices by conditions
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [33]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [34]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]
