SORTING AN ARRAY

In [2]:
import numpy as np
arr = np.random.rand(5,5)


In [3]:
print(np.sort(arr, axis=0)) #gives copy
arr.sort(axis=0)#sort along the row in place
print(arr)

[[0.01369529 0.07292177 0.0826583  0.08919504 0.28471194]
 [0.06437477 0.12720258 0.22003785 0.13440667 0.3084507 ]
 [0.17152621 0.16560441 0.57671752 0.23104387 0.37317921]
 [0.64262857 0.40198653 0.74234101 0.28034353 0.62032887]
 [0.8287447  0.5694065  0.97322563 0.59553068 0.78224104]]
[[0.01369529 0.07292177 0.0826583  0.08919504 0.28471194]
 [0.06437477 0.12720258 0.22003785 0.13440667 0.3084507 ]
 [0.17152621 0.16560441 0.57671752 0.23104387 0.37317921]
 [0.64262857 0.40198653 0.74234101 0.28034353 0.62032887]
 [0.8287447  0.5694065  0.97322563 0.59553068 0.78224104]]


In [ ]:
print(np.sort(arr, axis=1))#along a column

In [8]:
#compute the indices that would sort an array along a specified axis
arr = np.random.rand(5,5)
print(arr)

[[0.7426708  0.18729972 0.6838689  0.46921178 0.36504569]
 [0.82130831 0.08935809 0.21891025 0.57517838 0.26747996]
 [0.30302136 0.34446604 0.48041276 0.72904921 0.41983796]
 [0.27647718 0.08192307 0.81943237 0.76947317 0.23110459]
 [0.79030383 0.57294623 0.27541808 0.22704949 0.04129996]]


In [10]:
#Instead of sorting the elements themselves, it sorts the indices(positions) of the elements.
# to know which columns contain the smallest or largest values in each row.
print(np.argsort(arr, axis=0))#Row


[[3 3 1 4 4]
 [2 1 4 0 3]
 [0 0 2 1 1]
 [4 2 0 2 0]
 [1 4 3 3 2]]


In [7]:
print(np.argsort(arr, axis=1))#column

[[3 2 4 1 0]
 [4 1 2 3 0]
 [2 4 0 3 1]
 [1 0 2 4 3]
 [0 4 2 3 1]]


In [11]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[24 16  6  1  7 23 19  9 22 15 10 11  4 14  3 12 21  8  2 13  0 18 20 17
  5]


In [13]:
#TRANSPOSE ARRAY
arr = np.random.rand(3,4)
print(arr)

[[0.17881966 0.55654297 0.93356983 0.85880682]
 [0.71810656 0.91608811 0.54374449 0.05867548]
 [0.20682158 0.91556166 0.24873941 0.75751476]]


In [14]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.17881966 0.71810656 0.20682158]
 [0.55654297 0.91608811 0.91556166]
 [0.93356983 0.54374449 0.24873941]
 [0.85880682 0.05867548 0.75751476]]
[[0.17881966 0.71810656 0.20682158]
 [0.55654297 0.91608811 0.91556166]
 [0.93356983 0.54374449 0.24873941]
 [0.85880682 0.05867548 0.75751476]]
[[0.17881966 0.71810656 0.20682158]
 [0.55654297 0.91608811 0.91556166]
 [0.93356983 0.54374449 0.24873941]
 [0.85880682 0.05867548 0.75751476]]


In [15]:
#transpose of a high dimensional array with specified order of axes
arr1 = np.arange(16).reshape((2,2,4))#3dimentions
print(arr1)

arr2=arr1.transpose((1,0,2))
print(arr2)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [19]:
arr2 = np.arange(16).reshape((2,2,4))
print(arr2)
print(arr2.swapaxes(1,2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [38]:
arr=np.arange(16)
print(arr)
arr1=arr.reshape(4,2,2)
print(arr1)
arr.resize((4,2,2))
print(arr)
"""reshape() creates a new array with the specified shape without modifying the original, 
while resize() modifies the array itself to the specified shape and returns None."""

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [44]:
arr3=arr.flatten()    
print(arr3)
arr4=arr.ravel()
print(arr4) 

''' flatten() always returns a copy of the original data as a 1-dimensional array,
while ravel() attempts to return a view (reference) to the original data if possible, 
making it more memory efficient and faster for large arrays.
Use flatten() when you need a copy and
ravel() when you want efficiency and potentially need to modify the flattened array without 
affecting the original.
'''

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


' flatten() always returns a copy of the original data as a 1-dimensional array,\nwhile ravel() attempts to return a view (reference) to the original data if possible, \nmaking it more memory efficient and faster for large arrays.\nUse flatten() when you need a copy and\nravel() when you want efficiency and potentially need to modify the flattened array without \naffecting the original.\n'

In [45]:
# append an array and return a copy
arr5 = np.append(arr3, [4,5,6])    
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  4  5  6]


In [46]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr3, 0, 100)    
print(arr3)

[100   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]


In [47]:
# remove the element at position 0
arr3 = np.delete(arr, 0)    
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [49]:
# the following methods are all deep copy
arr3 = np.copy(arr)
# or 
arr3 = arr.copy()
# or 
arr6 = np.array(arr, copy=True)
print(arr6)


[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
