Combine & Split an Array

In [3]:
import numpy as np
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
print(arr1)
print(arr2)

[[1 2 3 4]
 [1 2 3 4]]
[[5 6 7 8]
 [5 6 7 8]]


In [5]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [4]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
#np.vstack((a, b))
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)
#np.r_[axis,a, b]
# stack arrays vertically  and increased number of rows.
cat = np.r_[arr1, arr2]
print(cat)


Difference:=
np.r_[] provides more flexibility as it supports concatenation along different axes (np.r_['-axis', arr1, arr2] for example), whereas np.vstack() specifically stacks arrays vertically along axis 0.
np.r_[] can be more concise when concatenating multiple arrays together in a single expression.

In [6]:
#np.hstack((a, b))
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)


[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [12]:
#np.c_[a, b]
# stack arrays horizontally
# increased number of columns.
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [13]:
# split the array vertically into n evenly spaced chunks
cat1= np.vsplit(cat, 2)
print(cat1)

[array([[1, 2, 3, 4, 5, 6, 7, 8]]), array([[1, 2, 3, 4, 5, 6, 7, 8]])]


In [14]:
cat= np.hsplit(cat, 2)
print(cat)

[array([[1, 2, 3, 4],
       [1, 2, 3, 4]]), array([[5, 6, 7, 8],
       [5, 6, 7, 8]])]


Set Operations
Set operations are used to manipulate sets and produce new sets. The most common set operations are:
Union: The union of two sets A and B, denoted by A ∪ B, is
Intersection: The intersection of two sets A and B, denoted by A ∩ B, is
Difference: The difference of two sets A and B, denoted by A - B, is
Symmetric Difference: The symmetric difference of two sets A and B, denoted by A Δ B
Cartesian Product: The Cartesian product of two sets A and B, denoted by A × B
Union of Sets
The union of two sets A and B, denoted by A ∪ B, is the set
of all elements that are in A or in B or in both.
A ∪ B = {x | x ∈ A or x ∈ B}
Example: If A = {1, 2, 3} and B = {3,
4, 5}, then A ∪ B = {1, 2, 3,
4, 5}.
Intersection of Sets
The intersection of two sets A and B, denoted by A ∩ B, is the set
of all elements that are in both A and B.
A ∩ B = {x | x ∈ A and x ∈ B}
Example: If A = {1, 2, 3} and B = {3,
4, 5}, then A ∩ B = {3}.
Difference of Sets


In [29]:
A = (1,2,3) 
B = (1,2,3,4,5)
AB= np.union1d(A,B)
print(AB)
c=np.intersect1d(A,B)
print(c)

[1 2 3 4 5]
[1 2 3]


In [38]:
print(np.in1d(A,B))# same length as test_elements.

print(np.in1d(B,A))

# preserve the shape of the array in the output, if the array is of higher dimensions
print(np.isin(A,B))# returns a boolean array of the same shape as test_elements.
print(np.isin(B,A))

'''Use np.isin() when you want to check membership against a broader range of list-like objects 
(including arrays, lists, and pandas objects).
Use np.in1d() when you specifically need to check membership against another NumPy array.'''

[ True  True  True]
[ True  True  True False False]
[ True  True  True]
[ True  True  True False False]


In [30]:
#select the unique elements from an array

arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [31]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [39]:
#compute the elements in an array that are not in another
print(np.setdiff1d(A,B))
#np.setdiff1d(A, B) gives elements in A but not in B.

#np.setxor1d(A, B) gives elements in either A or B, but not in both.
# set exclusive-or (XOR) of two arrays,
#compute the elements in either of two arrays, but not both
print(np.setxor1d(A,B))


[]
[4 5]


In [44]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)
#matrix multiplication
arr3 = np.dot(arr1,arr2)
print(arr3)
arr4 = np.random.rand(5,5)
arr5 = np.random.rand(5,5)
#matrix multiplication
arr6 = np.dot(arr4,arr5)
print(arr6)
#matrix addition
arr7 = arr3 + arr6
print(arr7)

print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[1.00534976 1.57523011 0.91902203 1.14630161 0.32328185]
 [1.08988277 1.27396956 0.59748247 0.77430382 0.5347902 ]
 [0.92457585 1.27406115 1.27887548 1.390375   1.15424317]
 [1.36267429 1.77046277 1.29899681 1.32838784 0.87480234]
 [0.63347652 0.56420775 0.58647716 0.79606457 0.95112434]]
[[1.95173173 2.20841822 2.26064623 1.71420221 1.59704564]
 [0.72457552 0.6054935  0.86852348 0.88032093 0.92698198]
 [1.35723528 1.51293201 1.56802236 1.3394696  1.26894904]
 [0.67927235 1.14100067 1.14963546 0.79223055 1.11620197]
 [1.37132428 1.78830303 1.55701129 1.09156004 0.92892403]]
[[2.95708149 3.78364833 3.17966826 2.86050382 1.92032749]
 [1.81445829 1.87946306 1.46600595 1.65462475 1.46177218]
 [2.28181113 2.78699316 2.84689784 2.7298446  2.42319221]
 [2.04194664 2.91146343 2.44863227 2.1206184  1.99100431]
 [2.0048008  2.35251077 2.14348845 1.88762461 1.88004838]]
[[1.00534976 1.57523011 0.91902203 1.14630161 0.32328185]
 [1.08988277 1.27396956 0.59748247 0.77430382 0.5347902 ]
 [0.9245758

In [51]:
#QR factorization
arr = np.random.rand(2,2)
print(arr)
q, r = np.linalg.qr(arr)
print(q)
print(r)

#q is the orthogonal/unitary matrix
#r is the upper triangular matrix

[[0.16790906 0.06604941]
 [0.79219612 0.82682402]]
[[-0.20734758 -0.97826734]
 [-0.97826734  0.20734758]]
[[-0.80979512 -0.82255011]
 [ 0.          0.10682598]]


In [49]:
#singular value decomposition (SVD)
arr = np.random.rand(1,2)
print(arr)
u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[0.21053964 0.42214891]]
[[-1.]]
[0.4717379]
[[-0.4463064  -0.89488022]
 [-0.89488022  0.4463064 ]]


In [52]:
#compute eigen values
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 3.24036926  0.69552137 -0.07332931 -0.00886919  0.16707458]


In [54]:
#eigen value decomposition
arr = np.random.rand(2,2)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[1.18055099 0.1840903 ]
[[ 0.88045156 -0.75623292]
 [ 0.47413611  0.65430251]]


In [55]:
#compute the trace & determinant
# notice this is not a function in linalg!!!
print(np.trace(arr))    
print(np.linalg.det(arr))

1.3646412906168612
0.2173279890202996


In [56]:
#calculate the inverse/psedo-inverse of a matrix
arr = np.random.rand(2,2)
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[-35.46515566   7.48329894]
 [ 21.56011502  -2.70943578]]


In [57]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))


[[-35.46515566   7.48329894]
 [ 21.56011502  -2.70943578]]


In [61]:
# solve a linear system in closed form

import numpy as np

# Create a coefficient matrix A (arr) and vector y
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 10]])  # Example coefficient matrix A
y = [1, 2, 3]  # Example vector y

# Compute the solution to the linear system Ax = y
solution = np.linalg.solve(arr, y)

# Print the solution vector x
print("Solution vector x:")
print(solution)


Solution vector x:
[-3.33333333e-01  6.66666667e-01  3.17206578e-17]


In [60]:
import numpy as np

# Create a matrix A (arr) and vector y
arr = np.random.rand(5, 3)  # Example matrix A
y = [1, 2, 3, 4, 5]  # Example vector y

# Compute the least-squares solution
solution, residuals, rank, singular = np.linalg.lstsq(arr, y, rcond=None)

# Print the results
print("Least-squares solution:")
print(solution)
print("Residuals:")
print(residuals)
print("Rank of matrix A:")
print(rank)
print("Singular values of matrix A:")
print(singular)


Least-squares solution:
[1.71291595 1.41987175 2.03976055]
Residuals:
[10.76922349]
Rank of matrix A:
3
Singular values of matrix A:
[2.30401635 0.82445122 0.35691166]
